variables:
    GIT_DEPTH: "1"

stages:
    - mil-internal-release_build
    - prepare_mil-internal-release_debs

mil-internal-release_build:
    tags:
        - Runner-Stretch
    stage: mil-internal-release_build
    only:
      variables:
        - $version
    before_script:
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20190909 stretch main" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - dpkg --add-architecture armhf
        - apt-get update
        - apt-get install -y --allow-unauthenticated build-essential crossbuild-essential-armhf
    script:
        - export TZ="Asia/Taipei"
        - export PKG_FW_VERSION=${version}
        - export PKG_BUILDDATE=$(date +%y%m%d%H)
        - dpkg-buildpackage -us -uc -b -aarmhf
        - echo "The package firmware version=${PKG_FW_VERSION}"
        - echo "The package build date=${PKG_BUILDDATE}"
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_mil-internal-release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_mil-internal-release_debs
    only:
      refs:
        - stretch/master
    dependencies:
        - mil-internal-release_build
    when: manual
    script:
        - mkdir -p /cache/stretch/mil-internal-release/
        - cp *.deb /cache/stretch/mil-internal-release/
        - ls /cache/stretch/mil-internal-release/
